function make()
    % Build the simple_math example MEX file.
    % Run from the examples/simple_math/ directory.

    mexforgeInclude = fullfile('..', '..', 'include');

    if ispc
        % Windows (MSVC)
        mex('-v', ...
            ['-I' mexforgeInclude], ...
            'COMPFLAGS=$COMPFLAGS /std:c++17 /bigobj', ...
            'bindings.cpp');
    elseif ismac
        % macOS (Xcode/Clang)
        mex('-v', ...
            ['-I' mexforgeInclude], ...
            'CXXFLAGS=$CXXFLAGS -std=c++17', ...
            'bindings.cpp');
    else
        % Linux (GCC)
        mex('-v', ...
            ['-I' mexforgeInclude], ...
            'CXXFLAGS=$CXXFLAGS -std=c++17', ...
            'bindings.cpp');
    end

    fprintf('Build complete. MEX file: %s\n', ['bindings.' mexext]);
end
