function generate_signatures(mexFunc, outputDir)
    % GENERATE_SIGNATURES  Generate tab-completion files for a MexForge binding.
    %
    % Creates two files in outputDir:
    %   1. functionSignatures.json  — enables argument hints in the MATLAB editor
    %   2. <mexname>_obj.m          — auto-generated subclass of MexObject with
    %                                 explicit method stubs for editor tab-completion
    %
    % Usage:
    %   mexforge.generate_signatures(@bindings)
    %   mexforge.generate_signatures(@bindings, './matlab')
    %
    % After running, use the generated class instead of MexObject:
    %   calc = bindings_obj("myCalc");   % full editor completion
    %   calc.add(2, 3)                   % IDE knows this method exists

    if nargin < 2
        outputDir = fileparts(which(func2str(mexFunc)));
        if isempty(outputDir)
            outputDir = pwd;
        end
    end

    mexName = func2str(mexFunc);

    % Collect method list
    try
        methods = cellstr(mexFunc("__list_methods"));
    catch
        allFuncs = cellstr(mexFunc("__list_functions"));
        methods = allFuncs(~startsWith(allFuncs, '_'));
        methods = setdiff(methods, {'create', 'destroy'});
    end

    % Collect metadata per method
    meta = collectMeta(mexFunc, methods);

    % 1) Write functionSignatures.json
    writeJson(outputDir, methods, meta);

    % 2) Write wrapper class
    writeClass(outputDir, mexName, methods, meta);
end

% --------------------------------------------------------------------------

function meta = collectMeta(mexFunc, methods)
    meta = struct();
    for i = 1:numel(methods)
        name  = methods{i};
        field = matlab.lang.makeValidName(name);
        try
            meta.(field).args = mexFunc("__arg_info", name);
        catch
            meta.(field).args = [];
        end
        try
            meta.(field).desc = char(mexFunc("__describe", name));
        catch
            meta.(field).desc = '';
        end
        try
            meta.(field).ret = char(mexFunc("__return_type", name));
        catch
            meta.(field).ret = '';
        end
    end
end

% --------------------------------------------------------------------------

function writeJson(outputDir, methods, meta)
    sigs = struct();
    for i = 1:numel(methods)
        name  = methods{i};
        field = matlab.lang.makeValidName(name);
        m     = meta.(field);

        inputs = {};
        for j = 1:numel(m.args)
            a      = struct();
            a.name = m.args(j).name;
            a.kind = 'required';
            if ~m.args(j).required
                a.kind = 'namevalue';
            end
            switch m.args(j).type
                case {'double', 'single'}
                    a.type = {{'numeric'}};
                case {'int32', 'uint32', 'int64', 'uint64', 'double[]'}
                    a.type = {{'integer'}};
                case {'string', 'char'}
                    a.type = {{'char', 'string'}};
                case 'logical'
                    a.type = {{'logical'}};
                case 'struct'
                    a.type = {{'struct'}};
                otherwise
                    a.type = {{'numeric'}};
            end
            inputs{end+1} = a; %#ok<AGROW>
        end

        entry = struct();
        if ~isempty(m.desc)
            entry.description = m.desc;
        end
        if ~isempty(inputs)
            entry.inputs = inputs;
        end
        sigs.(field) = entry;
    end

    outFile = fullfile(outputDir, 'functionSignatures.json');
    fid = fopen(outFile, 'w');
    fprintf(fid, '%s', jsonencode(sigs, 'PrettyPrint', true));
    fclose(fid);
    fprintf('  functionSignatures.json  (%d methods)\n', numel(methods));
end

% --------------------------------------------------------------------------

function writeClass(outputDir, mexName, methods, meta)
    className = [mexName '_obj'];
    lines     = {};

    function emit(s), lines{end+1} = s; end %#ok<NASGU>

    emit(sprintf('%% AUTO-GENERATED by mexforge.generate_signatures — do not edit manually.'));
    emit(sprintf('%% Regenerate: mexforge.generate_signatures(@%s)', mexName));
    emit(sprintf('classdef %s < mexforge.MexObject', className));
    emit(sprintf('    %% %s  Auto-generated wrapper for editor tab-completion.', upper(className)));
    emit(sprintf('    %% Use instead of mexforge.MexObject for full IDE support:'));
    emit(sprintf('    %%   calc = %s(constructor_args...);', className));
    emit(sprintf('    %%   calc.add(2, 3)   %% editor sees this method'));
    emit('');
    emit('    methods');
    emit(sprintf('        function obj = %s(varargin)', className));
    emit(sprintf('            obj@mexforge.MexObject(@%s, varargin{:});', mexName));
    emit('        end');
    emit('');

    for i = 1:numel(methods)
        name  = methods{i};
        field = matlab.lang.makeValidName(name);
        m     = meta.(field);

        % Split args into required and optional.
        % Use char() so reqArgs is always a cell of char vectors (strjoin requirement).
        reqArgs = {};
        hasOpt  = false;
        for j = 1:numel(m.args)
            if m.args(j).required
                reqArgs{end+1} = char(m.args(j).name); %#ok<AGROW>
            else
                hasOpt = true;
                break;
            end
        end

        % Build function signature line
        if isempty(reqArgs) && ~hasOpt
            sig      = sprintf('        function varargout = %s(obj)', name);
            callArgs = sprintf('"%s"', name);
        elseif hasOpt
            if isempty(reqArgs)
                sig = sprintf('        function varargout = %s(obj, varargin)', name);
                callArgs = sprintf('"%s", varargin{:}', name);
            else
                sig = sprintf('        function varargout = %s(obj, %s, varargin)', ...
                    name, strjoin(reqArgs, ', '));
                callArgs = sprintf('"%s", %s, varargin{:}', name, strjoin(reqArgs, ', '));
            end
        else
            sig = sprintf('        function varargout = %s(obj, %s)', ...
                name, strjoin(reqArgs, ', '));
            callArgs = sprintf('"%s", %s', name, strjoin(reqArgs, ', '));
        end

        % Comment
        commentStr = m.desc;
        if ~isempty(m.ret) && ~strcmp(m.ret, 'void')
            commentStr = sprintf('%s → %s', commentStr, m.ret);
        end

        emit(sig);
        if ~isempty(commentStr)
            emit(sprintf('            %% %s', commentStr));
        end
        emit(sprintf('            [varargout{1:nargout}] = callMethod(obj, %s);', callArgs));
        emit('        end');
        emit('');
    end

    emit('    end');
    emit('end');

    outFile = fullfile(outputDir, [className '.m']);
    fid = fopen(outFile, 'w');
    for k = 1:numel(lines)
        fprintf(fid, '%s\n', lines{k});
    end
    fclose(fid);
    fprintf('  %s.m  (%d methods)\n', className, numel(methods));
    fprintf('Usage: calc = %s(constructor_args...);\n', className);
end
